name: ${COMPOSE_PROJECT_NAME}
services:
  postgis:
    image: postgis/postgis:16-3.5
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: qa_postgis_db
    ports:
      - "${POSTGIS_PORT}:5432"
    volumes:
      - postgis_data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - qa_net

  grafana:
    image: grafana/grafana:12.4.0-20151846001
    environment:
      GF_SECURITY_ADMIN_PASSWORD: admin
    ports:
      - "${GRAFANA_PORT}:3000"
    depends_on:
      - postgis
    restart: unless-stopped
    networks:
      - qa_net

  qa:
    image: histotools/quickannotator:main
    volumes:
      # nas_read can be replaced with a local or NAS mount.
      - nas_read:/opt/QuickAnnotator/quickannotator/mounts/nas_read 
      - nas_write:/opt/QuickAnnotator/quickannotator/mounts/nas_write
    networks:
      - qa_net
    depends_on:
      - postgis
    environment:
      - POSTGRES_HOST=postgis
    ports:
      - "${VITE_PORT}:5173"
      - "${QA_PORT}:5000"
      - "${RAY_PORT}:8265"
      - "${TB_PORT}:6006"
    command:
      - /bin/bash
      - -lc
      - |
          tmux new-session -d -s server "quickannotator"
          tmux new-session -d -s ui "npm run dev"
          tail -f /dev/null
    stdin_open: true
    tty: true
    shm_size: '12gb'
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            count: all
            capabilities: [gpu]


networks:
  qa_net:
    driver: bridge

volumes:
  postgis_data:
  nas_read:
  nas_write:
  # qadb_data: # only needed if using sqlite db